import Link from "next/link";
import Image from "next/image"; // <--- 1. Import this
import { ArrowRight, Download, Terminal } from "lucide-react";
import { heroData } from "@/lib/data";

export default function Hero() {
  return (
    <section className="relative flex min-h-[calc(100vh-4rem)] items-center justify-center overflow-hidden py-20">
      
      
      <div className="absolute inset-0 -z-20">
        <Image
          src="/backgroundHero.webp"
          alt="Abstract technology background generated by AI"
          fill
          className="object-cover" // Ensures image covers area without stretching
          priority // Tells browser to load this image first (for speed)
        />
      </div>
      <div className="absolute inset-0 -z-10 bg-slate-900/80" />
      


      <div className="container relative z-10 mx-auto px-4 text-center md:text-left">
        <div className="flex flex-col items-center gap-12 md:flex-row md:items-start md:justify-between">
          
          {/* Text Content */}
          <div className="max-w-2xl space-y-6">
            {/* Badge */}
            <div className="inline-flex items-center rounded-full border border-blue-400/30 bg-blue-900/30 px-3 py-1 text-sm text-blue-300 backdrop-blur-md">
              <Terminal className="mr-2 h-3 w-3" />
              <span>Full-Stack Engineer & Ops Specialist</span>
            </div>

            {/* Changed text color to white for contrast against dark background */}
            <h1 className="text-4xl font-bold tracking-tight text-white sm:text-6xl">
              {heroData.headline}
            </h1>
            
            <p className="text-lg text-slate-300 md:text-xl">
              {heroData.subheadline}
            </p>

            {/* Buttons */}
            <div className="flex flex-col gap-4 sm:flex-row sm:justify-center md:justify-start">
              <Link
                href="/#projects"
                className="inline-flex items-center justify-center rounded-lg bg-blue-600 px-6 py-3 text-sm font-medium text-white shadow-lg transition-colors hover:bg-blue-700"
              >
                View Work
                <ArrowRight className="ml-2 h-4 w-4" />
              </Link>

              <a
                href="/David_Caldwell_Resume.pdf"
                download
                className="inline-flex items-center justify-center rounded-lg border border-white/20 bg-white/10 px-6 py-3 text-sm font-medium text-white shadow-sm backdrop-blur-sm transition-colors hover:bg-white/20"
              >
                Download Resume
                <Download className="ml-2 h-4 w-4" />
              </a>
            </div>
          </div>

          {/* Visual Element (Right Side) */}
          <div className="hidden w-full max-w-md md:block">
            <div className="rounded-xl border border-white/10 bg-white/5 p-6 shadow-2xl backdrop-blur-md">
               <div className="mb-4 flex space-x-2">
                 <div className="h-3 w-3 rounded-full bg-red-500" />
                 <div className="h-3 w-3 rounded-full bg-amber-500" />
                 <div className="h-3 w-3 rounded-full bg-green-500" />
               </div>
               <div className="space-y-3 font-mono text-sm">
                 <div className="flex text-slate-400">
                   <span className="mr-4 text-slate-600">1</span>
                   <span>class <span className="text-yellow-400">HybridEngineer</span> &#123;</span>
                 </div>
                 <div className="flex text-slate-400">
                    <span className="mr-4 text-slate-600">2</span>
                    <span className="ml-4">hardware: <span className="text-green-400">&quot;Expert&quot;</span>;</span>
                 </div>
                 <div className="flex text-slate-400">
                    <span className="mr-4 text-slate-600">3</span>
                    <span className="ml-4">software: [<span className="text-green-400">&quot;React&quot;</span>, <span className="text-green-400">&quot;AWS&quot;</span>];</span>
                 </div>
                 <div className="flex text-slate-400">
                    <span className="mr-4 text-slate-600">4</span>
                    <span className="ml-4">mission: <span className="text-green-400">&quot;Bridge the gap.&quot;</span>;</span>
                 </div>
                 <div className="flex text-slate-400">
                    <span className="mr-4 text-slate-600">5</span>
                    <span>&#125;</span>
                 </div>
               </div>
            </div>
          </div>

        </div>
      </div>
    </section>
  );
}