import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import Header from "@/components/Header"; 
import Footer from "@/components/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "David Caldwell",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    // 2. 'scroll-smooth' makes jumping to #projects feel nice
    <html lang="en" className="scroll-smooth">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased flex flex-col min-h-screen`}
      >
        
        {/* THE CEILING: Fixed Header */}
        <Header />

        {/* THE ROOM: The actual page content */}
        {/* 'flex-grow' pushes the Footer down. 'pt-16' stops the Header from covering the Hero. */}
        <main className="flex-grow pt-16">
          {children}
        </main>

        {/* THE FLOOR: Static Footer */}
        <Footer />
        
      </body>
    </html>
  );
}
